-- MIGRAÇÃO FINAL SEGURA - VIGIVAGAS
-- Roda no PostgreSQL/Render. Não apaga dados nem tabelas.

-- AUDITORIA
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_type TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- LGPD / CONSENTIMENTOS
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS user_type TEXT;
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS policy_version TEXT DEFAULT '1.0';
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS terms_version TEXT DEFAULT '1.0';
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS consent_text TEXT;
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE lgpd_consents ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- VAGAS / OPORTUNIDADES ENCERRADAS
ALTER TABLE vagas ADD COLUMN IF NOT EXISTS encerrada_em TIMESTAMP;
ALTER TABLE vagas
  ALTER COLUMN encerrada_em TYPE TIMESTAMP
  USING NULLIF(encerrada_em::text, '')::timestamp;
ALTER TABLE vagas ADD COLUMN IF NOT EXISTS encerrada_motivo_tipo TEXT;
ALTER TABLE vagas ADD COLUMN IF NOT EXISTS encerrada_motivo TEXT;
ALTER TABLE vagas ADD COLUMN IF NOT EXISTS vigivagas_ajudou_contratacao TEXT;
ALTER TABLE vagas ADD COLUMN IF NOT EXISTS contratacoes_quantidade INTEGER DEFAULT 0;
ALTER TABLE vagas ADD COLUMN IF NOT EXISTS encerrada_observacoes TEXT;
CREATE INDEX IF NOT EXISTS idx_vagas_encerrada_em ON vagas (encerrada_em);
